language: node_js
node_js: node

cache:
  yarn: true
  directories:
    - node_modules

before_script: yarn install-peers
script:
  - yarn lint
  - yarn build
  - yarn ci:test
after_success:
  - yarn ci:report
