language: node_js
node_js: "8"

notifications:
  email: false

cache:
  yarn: true
  directories:
    - node_modules

before_script: yarn before-script
script:
  - yarn lint
  - yarn build
  - yarn test
after_success:
  - yarn ci:report
